### ISSUE TITLE
share CAS-ENT records without taxonomic information

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/cas-ent#3]
For Jorrit to share a list of CAS-ENT catalog numbers that GloBI couldn't find taxonomic names for. and for @chrisgrinter to cross check that list against Symbiota portal.

**Comment by jhpoelen** [comment]
Here's the list of records without taxonomic names:

"CAS | ENT | 8115073 | urn:catalog:CAS:ENT:8115073"
"CAS | ENT | 8115073 | urn:catalog:CAS:ENT:8115073"
"CAS | ENT | 8115074 | urn:catalog:CAS:ENT:8115074"
"CAS | ENT | 8115076 | urn:catalog:CAS:ENT:8115076"
"CAS | ENT | 8115077 | urn:catalog:CAS:ENT:8115077"
"CAS | ENT | 8115078 | urn:catalog:CAS:ENT:8115078"
"CAS | ENT | 90504 | urn:catalog:CAS:ENT:90504"
"CAS | ENT | 8325868 | urn:catalog:CAS:ENT:8325868"
"CAS | ENT | 8325902 | urn:catalog:CAS:ENT:8325902"
"CAS | ENT | 8325903 | urn:catalog:CAS:ENT:8325903"
"CAS | ENT | 8325917 | urn:catalog:CAS:ENT:8325917"
"CAS | ENT | 9026242 | urn:catalog:CAS:ENT:9026242"
"CAS | ENT | 9026243 | urn:catalog:CAS:ENT:9026243"
"CAS | ENT | 9026244 | urn:catalog:CAS:ENT:9026244"
"CAS | ENT | 9026245 | urn:catalog:CAS:ENT:9026245"
"CAS | ENT | 9026258 | urn:catalog:CAS:ENT:9026258"
"CAS | ENT | 9026259 | urn:catalog:CAS:ENT:9026259"
"CAS | ENT | 9026260 | urn:catalog:CAS:ENT:9026260"
"CAS | ENT | 9026261 | urn:catalog:CAS:ENT:9026261"
"CAS | ENT | 9026262 | urn:catalog:CAS:ENT:9026262"
"CAS | ENT | 9022980 | urn:catalog:CAS:ENT:9022980"
"CAS | ENT | 9023555 | urn:catalog:CAS:ENT:9023555"
"CAS | ENT | 9024621 | urn:catalog:CAS:ENT:9024621"
"CAS | ENT | 9024622 | urn:catalog:CAS:ENT:9024622"
"CAS | ENT | 9024623 | urn:catalog:CAS:ENT:9024623"
"CAS | ENT | 9024635 | urn:catalog:CAS:ENT:9024635"
"CAS | ENT | 9024636 | urn:catalog:CAS:ENT:9024636"
"CAS | ENT | 9027550 | urn:catalog:CAS:ENT:9027550"
"CAS | ENT | 9027551 | urn:catalog:CAS:ENT:9027551"
"CAS | ENT | 9027724 | urn:catalog:CAS:ENT:9027724"
"CAS | ENT | 9028130 | urn:catalog:CAS:ENT:9028130"
"CAS | ENT | 9028131 | urn:catalog:CAS:ENT:9028131"
"CAS | ENT | 9028135 | urn:catalog:CAS:ENT:9028135"
"CAS | ENT | 9028136 | urn:catalog:CAS:ENT:9028136"
"CAS | ENT | 9028137 | urn:catalog:CAS:ENT:9028137"
"CAS | ENT | 9028138 | urn:catalog:CAS:ENT:9028138"
"CAS | ENT | 9028139 | urn:catalog:CAS:ENT:9028139"
"CAS | ENT | 9035069 | urn:catalog:CAS:ENT:9035069"
"CAS | ENT | 9035070 | urn:catalog:CAS:ENT:9035070"

@ChrisGrinter please double check thanks!

**Comment by jhpoelen** [comment]
Note that only records with some suspected interaction data are considered.

**Comment by ChrisGrinter** [comment]
These have all been resolved. They were undetermined spiders = Araneae
